import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

def run_cmd(cmd):
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        return result
    except Exception as e:
        return subprocess.CompletedProcess(args=cmd, returncode=-1, stdout="", stderr=str(e))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--shrink-baseline", action="store_true")
    parser.add_argument("--ci", action="store_true")
    parser.parse_args()

    cwd = Path.cwd()
    gate_report = {
        "schema_version": "1.0",
        "analysis": {"errors": 0, "warnings": 0, "violations": []},
        "size": {"violations": [], "largest_file": 0, "p90_file": 0},
        "struct": {"violations": []},
        "tests": {"total": 0, "passed": 0, "failed": 0, "failures": []},
        "coverage": {"pct": "n/a"}
    }
    
    failures = {
        "G1": [],
        "G2": [],
        "G3": [],
        "G4": [],
        "G5": [],
        "G6": []
    }

    # G1: ruff and mypy
    ruff_res = run_cmd(["uv", "run", "ruff", "check", "--output-format=json"])
    try:
        ruff_data = json.loads(ruff_res.stdout) if ruff_res.stdout else []
    except Exception:
        ruff_data = []
    
    for item in ruff_data:
        gate_report["analysis"]["errors"] += 1
        failures["G1"].append(f"[G1 ruff] {item.get('location', {}).get('row', 0)}: {item.get('message', '')} ({item.get('filename', '')})")

    mypy_res = run_cmd(["uv", "run", "mypy", "src", "tests"])
    for line in mypy_res.stdout.splitlines():
        if "error:" in line:
            gate_report["analysis"]["errors"] += 1
            failures["G1"].append(f"[G1 mypy] {line.strip()}")

    # G2: Size ratchet
    src_dir = cwd / "src"
    sizes = []
    if src_dir.exists():
        for py_file in src_dir.rglob("*.py"):
            try:
                with open(py_file, "r", encoding="utf-8") as f:
                    lines = len(f.readlines())
                    sizes.append(lines)
                    if lines > 300:
                        failures["G2"].append(f"[G2 size] {py_file.relative_to(cwd)} {lines} > baseline 300")
            except Exception:
                pass
    if sizes:
        sizes.sort()
        gate_report["size"]["largest_file"] = sizes[-1]
        gate_report["size"]["p90_file"] = sizes[int(len(sizes)*0.9)]

    # G3: Structural rules & G6: Security Anti-Patterns
    if src_dir.exists():
        for py_file in src_dir.rglob("*.py"):
            try:
                with open(py_file, "r", encoding="utf-8") as f:
                    content = f.read()
                    for idx, line in enumerate(content.splitlines()):
                        # G3 checks
                        if re.match(r'^\s*from\s+.*\s+import\s+\*', line) or re.match(r'^\s*import\s+\*', line):
                            failures["G3"].append(f"[G3 import] {py_file.relative_to(cwd)}:{idx+1}: {line.strip()}")
                            
                        # G6 checks (Security anti-patterns)
                        if "shell=True" in line.replace(" ", ""):
                            failures["G6"].append(f"[G6 security] {py_file.relative_to(cwd)}:{idx+1}: shell=True is forbidden.")
                        if re.search(r'os\.system\s*\(', line):
                            failures["G6"].append(f"[G6 security] {py_file.relative_to(cwd)}:{idx+1}: os.system() is forbidden. Use process_manager.")
                        if re.search(r'os\.popen\s*\(', line):
                            failures["G6"].append(f"[G6 security] {py_file.relative_to(cwd)}:{idx+1}: os.popen() is forbidden. Use process_manager.")
            except Exception:
                pass

    # G4 & G5: Tests and Coverage
    test_res = run_cmd(["uv", "run", "pytest", "--json-report", "-q", "--cov", "--cov-report=json"])
    # Read .report.json generated by pytest-json-report
    report_json_path = cwd / ".report.json"
    if report_json_path.exists():
        with open(report_json_path, "r", encoding="utf-8") as f:
            t_data = json.load(f)
            gate_report["tests"]["total"] = t_data.get("summary", {}).get("total", 0)
            gate_report["tests"]["passed"] = t_data.get("summary", {}).get("passed", 0)
            gate_report["tests"]["failed"] = t_data.get("summary", {}).get("failed", 0)
            for test in t_data.get("tests", []):
                if test.get("outcome") == "failed":
                    fail_msg = test.get("call", {}).get("crash", {}).get("message", "Unknown error")
                    failures["G4"].append(f"[G4 test] {test.get('nodeid')} {fail_msg}")
    else:
        failures["G4"].append("[G4 test] .report.json not generated (pytest failed?)")
        if test_res.returncode != 0:
            failures["G4"].append(test_res.stdout.splitlines()[0] if test_res.stdout else "Unknown error")
            
    # Read coverage.json
    cov_json_path = cwd / "coverage.json"
    if cov_json_path.exists():
        with open(cov_json_path, "r", encoding="utf-8") as f:
            c_data = json.load(f)
            gate_report["coverage"]["pct"] = round(c_data.get("totals", {}).get("percent_covered", 0), 2)
            
    gate_report["size"]["violations"] = failures["G2"]
    gate_report["struct"]["violations"] = failures["G3"]
    gate_report["analysis"]["violations"] = failures["G1"]
    gate_report["tests"]["failures"] = failures["G4"]
    # We can stuff G6 violations into analysis or a separate field, but keeping it simple for print out:
    # If there are any G6 violations, we will flag it in the print block

    with open(cwd / "gate_report.json", "w", encoding="utf-8") as f:
        json.dump(gate_report, f, indent=2)

    try:
        sha_res = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, check=True)
        sha = sha_res.stdout.strip()
    except Exception:
        sha = "unknown"

    passed_tests = gate_report["tests"]["passed"]
    total_tests = gate_report["tests"]["total"]
    e = gate_report["analysis"]["errors"]
    w = gate_report["analysis"]["warnings"]
    size_v = len(failures["G2"])
    struct_v = len(failures["G3"])
    security_v = len(failures["G6"])
    cov = gate_report["coverage"]["pct"]

    is_pass = (e == 0 and size_v == 0 and struct_v == 0 and security_v == 0 and gate_report["tests"]["failed"] == 0 and not failures["G4"])
    
    if is_pass:
        print(f"GATE PASS  sha={sha}  tests={passed_tests}/{total_tests}  analysis={e}E/{w}W  size={size_v}  struct={struct_v}  sec={security_v}  cov={cov}%")
        sys.exit(0)
    else:
        print(f"GATE FAIL  sha={sha}")
        for cat in ["G1", "G2", "G3", "G4", "G5", "G6"]:
            cat_fails = failures[cat]
            if not cat_fails:
                continue
            for msg in cat_fails[:15]:
                print(msg)
            if len(cat_fails) > 15:
                print(f"({len(cat_fails) - 15} more)")
        sys.exit(1)

if __name__ == "__main__":
    main()
